### ISSUE TITLE
Unexpected error when replicating experiments

### ISSUE THREAD

**Issue by ChenDRAG** [FoundationVision/LlamaGen#17]
Hi, I have a problem when reproducing experiments according to readme instructions, could you give me any clue for the potential reasons?

Using all official codes and tokenizer and only train a new GPT-B model on 256*256 images, I get the following sampled images, ALL looking like this (texture-style):
![image](https://github.com/FoundationVision/LlamaGen/assets/40993476/c8415bdb-6684-4dc5-a4f3-fa660b28d884)
![image](https://github.com/FoundationVision/LlamaGen/assets/40993476/f9498ba5-16c7-4ef6-8683-ff2b1e6e8a23)
![image](https://github.com/FoundationVision/LlamaGen/assets/40993476/fc8c81af-8c9b-4869-9a72-ee7783bc538d)

The only difference from the official instructions is that I use 8  40Gb A100 instead of 8  80Gb A100. Plus, I extract both imagnet train/eval dataset codes.

I'm basically certain there are no problems with image code extracting (because I verify images using check_image_codes.py and find no problems.) There should be no problem with image sampling, I sampled from the officially released model and it is okay.

Specifically, My experiment scripts are
1) extract codes for imagenet (both train and eval subsets) using provided image encoder:
`bash scripts/autoregressive/extract_codes_c2i.sh --vq-ckpt ./vq_ds16_c2i.pt --data-path /workspace/home/LargeData/Large/ImageNet/--code-path  ./imagenet_train_code_c2i_flip_ten_crop --ten-crop --crop-range 1.1 --image-size 256`
2) Train GPT-B AR model:
```
nnodes=1
nproc_per_node=8
node_rank=0
master_addr="127.0.0.1"
master_port=29502

torchrun \
--nnodes=$nnodes --nproc_per_node=$nproc_per_node --node_rank=$node_rank \
--master_addr=$master_addr --master_port=$master_port \
autoregressive/train/train_c2i.py --global-batch-size 256 --cloud-save-path /raid/data/huayu/LlamaGen_models --code-path /raid/data/huayu/imagenet_code_c2i_flip_ten_crop/ --image-size 256 --gpt-model GPT-B

```
3. Sample images using provided scripts.

Thank you for your help!

**Comment by ChenDRAG** [comment]
It was due to my stupid problem. Sorry for the inconvenience.

**Comment by Artanic30** [comment]
Hi, thanks for your great work. Could you provide more details on this bug? I'm currently running this code and wondering if my experiments are wrong due to this bug.

**Comment by ChenDRAG** [comment]
@Artanic30  I give the wrong data folder when extracting image code,
`bash scripts/autoregressive/extract_codes_c2i.sh --vq-ckpt ./vq_ds16_c2i.pt --data-path /workspace/home/LargeData/Large/ImageNet/--code-path  ./imagenet_train_code_c2i_flip_ten_crop --ten-crop --crop-range 1.1 --image-size 256`
should be 
`bash scripts/autoregressive/extract_codes_c2i.sh --vq-ckpt ./vq_ds16_c2i.pt --data-path /workspace/home/LargeData/Large/ImageNet/train --code-path  ./imagenet_train_code_c2i_flip_ten_crop --ten-crop --crop-range 1.1 --image-size 256`

The first command somehow results in normal image codes but wrong image labels. (All 0)
