### ISSUE TITLE
Question about text-conditional generation.

### ISSUE THREAD

**Issue by Yangr116** [FoundationVision/LlamaGen#30]
Great work!

I would like to know how you fine-tune the image tokenizer before the two-stage training for text conditional generation. Could you please provide some details, such as the image resolution and any other relevant information?

**Comment by PeizeSun** [comment]
Hi~
You can refer [train_vq_finetune](https://github.com/FoundationVision/LlamaGen/blob/main/scripts/tokenizer/train_vq_finetune.sh), which fine-tune the vq_ds16_c2i.pt and obtains vq_ds16_t2i.pt

**Comment by Yangr116** [comment]
Thanks!
