### ISSUE TITLE
Inquiry about the OpenImages dataset

### ISSUE THREAD

**Issue by RobertLuo1** [FoundationVision/LlamaGen#32]
Thanks for your great work!
May I know which version of OpenImages you utilize for the training? 1.8M or 9.2M?
Can you provide more information with https://github.com/FoundationVision/LlamaGen/blob/f7e28e0a4fd4625a9a7636f1b6f6f49792bd98a9/tools/openimage_json.py#L44.
Thank you in advance!

**Comment by PeizeSun** [comment]
Hi~
In our released models, we don’t use OpenImages.

**Comment by RobertLuo1** [comment]
Thanks for your quick reply. Do you know which version of OpenImages (v1 v4 v5 v6 v7) VQGAN uses for training, as I noticed that the result is included in the comparison. 

Thank you very much!
