### ISSUE TITLE
Questions about the discriminator

### ISSUE THREAD

**Issue by Doctor-James** [FoundationVision/LlamaGen#35]
Follow issue https://github.com/FoundationVision/LlamaGen/issues/27
I would like to ask if the discriminator's logit_real and logit_fake are always similar, and when they are both positive, the discriminator_adv_loss will be negative. Is such a discriminator beneficial to the generator?

**Comment by PeizeSun** [comment]
Hi~
I understand this is magic. But I highly recommend to run other GAN codebases to see this magic phenomena.
